### ISSUE TITLE
Crash and timeout on startup

### ISSUE THREAD

**Issue by mezz** [KidsDontPlay/BlockDrops#1]
This mod crashes on startup
log: https://gist.github.com/mezz/26c19126efd8f1fd8c1ac61e66daf494

original issue:
https://github.com/mezz/JustEnoughItems/issues/305

Technic pack used:
http://www.technicpack.net/modpack/legend-of-the-giant-squid.855398

**Comment by KidsDontPlay** [comment]
fixed.
I did not expect that a block could drop a null itemstack.
Which block should do that?

**Comment by mezz** [comment]
There are many broken blocks and items in 1.9.4 still. I have to check for null items inside an itemStack too.
