### ISSUE TITLE
Feature Request: Better drop calculation or manual edit of blockdrops

### ISSUE THREAD

**Issue by QuImUfu** [KidsDontPlay/BlockDrops#11]
Some mods edit block drops using the HarvestDropsEvent. This is not recognized by this mod, and i think it would be very hard to implement this, but i do not know much about coding, so this may be totally wrong.  
If this is reasonably easy i would be very grateful if you could add these block drop changes (via HarvestDropsEvent) to you block drop calculation. (here is an [example](https://github.com/UpcraftLP/Hardcore-Survival-1.10/blob/master/src/main/java/mod/upcraftlp/hardcoresurvival/util/LeafEvents.java) of a mod using this method)  
I think an good alternative (if this is not reasonable) would be a possibility to overwrite block drops and chances displayed by this mod via a config. This way e.g. i could look up the drops in the others mods (decompiled) source or ask the author and add them to your mods block drops in my personal modpack.

**Comment by KidsDontPlay** [comment]
Ok, HarvestDropsEvent works. I tested it with ExtraUtils.

Adding custom drops is already possible. in the config folder is the blockdrops.key file. You can add drops manually

**Comment by QuImUfu** [comment]
The drops added by the mod i linked to as example do not work. Maybe this mod does something wired/special?

So i just can edit this file without your mod overwriting it? Great! Is my assumption correct that it will get overridden everytime i add/remove mods? Maybe you could explain this on the CurseForge page.

Thank you for you fast and friendly answers and fixes. :+1:

**Comment by KidsDontPlay** [comment]
No, no. I implemented the support for harvestdrops event just yesterday. So it couldnt work you. Wait for the next release.

You're right. The file will be recreated if you change your mods
