### ISSUE TITLE
1.0.8 EXTREMELY slow

### ISSUE THREAD

**Issue by C0rn3j** [KidsDontPlay/BlockDrops#12]
BlockDrops-1.10.2-1.0.8.jar

Forge 2043.

It went from being "wait a minute or two to have it load" to "wait a minute or two to have one item analysed"

This is what happens after about 20 minutes http://i.imgur.com/kcDllgh.png

Mod list http://pastebin.com/Ls5P2BML

**Comment by C0rn3j** [comment]
Loaded just fine on second bootup, didn't seem to analyze blocks at all? O.o

the game process was using 7 out of 8 threads fully.

**Comment by the-creamster** [comment]
I can confirm this as it was causing the java process to max out my CPU(from approx 35% normal modpack CPU load with my usual array of running programs to 100%) the instant i launched the instance.
