### ISSUE TITLE
[ModCompat] EntityPlayer initialisation in Post-Init

### ISSUE THREAD

**Issue by maxanier** [KidsDontPlay/BlockDrops#13]
Hello,

there is a mod compat issue with your mod and my mod Vampirism.
Vampirism listens to the AttachCapability Event for entities to attach a capability and that capability requires things which are only created during post init, because it waits for information or addition from other mods (during init).
But you are already instantiating a EntityPlayer during Post-Init, which is not intended to by Forge (at least I think so), and causes the problem, since it is done before Vampirism post init is executed.

I probably could create a workaround in Vampirism, but it wouldn't be a very clean solution and could cause more problems. Most likely there are also other mods out there which do similar things. Is there a way you could instantiate the EntityPlayer later or to put your mod at the end of the mod order list?

Thanks,
Maxanier

**Comment by KidsDontPlay** [comment]
warum machste nich einfach ein nullcheck?

**Comment by maxanier** [comment]
As I said, I could do a simple workaround, but that might cause other issue, because the requested value (which is null at that point) will be used afterwards. 
Therefore(and also because it could affect other mods as well) I asked you, if it is possible to avoid doing things, which probably are not intended by Forge's design.
If you decide to not do so, I can still implement a workaround so our mods can be used together.
