### ISSUE TITLE
Newest version of block drops stalls out on Post-init

### ISSUE THREAD

**Issue by DatrixTHLK** [KidsDontPlay/BlockDrops#14]
With some mods installed the mod Block drops starts to freeze and then stalls out but doesn't close out. It starts out fine then once it hits certain mods the mod stops.

forge: 12.18.1.2046
Block Drop: 1.0.9
JEI: 3.7.10.237

**Comment by DatrixTHLK** [comment]
Same thing happens with EnderIO

Block Drop: 1.0.9
JEI: 3.7.10.237
EnderCore: 0.4.1.46
EnderIO: 3.0.1.81
forge: 12.18.1.2046

**Comment by DatrixTHLK** [comment]
After I downgrade to forge 2043 the errors went away. So it isn't this mods fault it is forge's update that caused mods to break I shall close the issue

**Comment by KidsDontPlay** [comment]
please show me your log file

**Comment by DatrixTHLK** [comment]
Log File: https://www.pastefs.com/pid/3769 (Sorry pastebin wouldn't allow more than 500kb per paste)

**Comment by KidsDontPlay** [comment]
Is it fixed with the latest version?

**Comment by DatrixTHLK** [comment]
Sorry for the late response. My graphics card is dead and the new graphics card will be in around 5-25 days from now. I will be able to test by the end of september.

**Comment by aureagle** [comment]
pastefs exceeds pastebin in many ways, why would someone apologize for using pastefs instead of pastebin? I hope your issue is resolved

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :(

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Unfortunately, my computer has been corrupted and don't have an operating system on it anymore. I won't be able to test anything until further notice. :( 

Yeah  you are correct aureagle, I didn't really need to appologize for that. In my mind I did because it wasn't pastebin. Anyway...If the issue is fixed then there isn't a reason to keep this open.

**Comment by DatrixTHLK** [comment]
Yes
1.0.11 fixes the freeze up on post-init
