### ISSUE TITLE
[Suggestion] Async block dropping

### ISSUE THREAD

**Issue by MakerTim** [KidsDontPlay/BlockDrops#17]
I dont know if it is possible; but if it can

make 2-4 threads for the blockdropping
the loading still takes a fair bit of time; especially with big mods like 'Pam's harvastcraft'
if you can, plz allow multi threading!

**Comment by KidsDontPlay** [comment]
I'm not familiar with threads

**Comment by durandj** [comment]
What if as an alternative to threading the loading process you could cache the data to disk to save loading time on subsequent game starts. This could use the mod version as a key. I can look at creating a PR if you think this could be valuable and is inline with what you want for the mod.

**Comment by KidsDontPlay** [comment]
I already save the data to disk

**Comment by MakerTim** [comment]
https://github.com/MrRiegel/BlockDrops/pull/40
Made a PR for it, that handels it in Async :D

**Comment by KidsDontPlay** [comment]
thx
I totally forgot your PR
