### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by HendrikJ79** [KidsDontPlay/BlockDrops#22]
Version: 1.0.11

Log File: [crash-2016-09-20_18.46.34-client.txt](https://github.com/MrRiegel/BlockDrops/files/483157/crash-2016-09-20_18.46.34-client.txt)

**Comment by KidsDontPlay** [comment]
try deleting blockdrops.key in config folder

**Comment by HendrikJ79** [comment]
Could'nt find a blockdrops.key in the config directory, only a blockdrops.cfg, after deleting this file it created a Blockdrop folder in config folder.

After a short test not any crash, but for safety my lastest log (personaly not checked on warnings or errors): [latest.log](https://gist.github.com/HendrikJ79/40cfe4eaa292d3fefd2db91d4162b1be)

**Update:** After updating some mods still a crash, even with deleting blockdrops.key and completely removing Blockdrops folder

Log: [crash-2016-09-20_21.51.44-client.txt](https://github.com/MrRiegel/BlockDrops/files/483493/crash-2016-09-20_21.51.44-client.txt)

**Comment by KidsDontPlay** [comment]
may you try this one
https://github.com/MrRiegel/mrriegel.github.io/raw/master/BlockDrops-1.10.2-1.0.12.jar

**Comment by HendrikJ79** [comment]
Still a crash when starting up: [crash-2016-09-21_09.15.04-client.txt](https://github.com/MrRiegel/BlockDrops/files/484339/crash-2016-09-21_09.15.04-client.txt)
Starting up took me about 15 minutes and file fml-client-latest is like 140Mb

Even I found several Warnings to detect seeds from MysticalCrops: 

> [09:03:40] [Client thread/WARN] [FML/blockdrops]: ****************************************
> [09:03:40] [Client thread/WARN] [FML/blockdrops]: \* No seeds detected!
> [09:03:40] [Client thread/WARN] [FML/blockdrops]: \*  at com.mysticalcrops.blocks.MysticalCropBlock.getSeeds(MysticalCropBlock.java:62)
> [09:03:40] [Client thread/WARN] [FML/blockdrops]: \*  at com.mysticalcrops.blocks.MysticalCropBlock.func_180660_a(MysticalCropBlock.java:112)
> [09:03:40] [Client thread/WARN] [FML/blockdrops]: \*  at com.mysticalcrops.blocks.MysticalCropBlock.getDrops(MysticalCropBlock.java:175)
> [09:03:40] [Client thread/WARN] [FML/blockdrops]: \*  at mrriegel.blockdrops.Plugin.getList(Plugin.java:105)
> [09:03:40] [Client thread/WARN] [FML/blockdrops]: \*  at mrriegel.blockdrops.Plugin.getRecipes(Plugin.java:81)
> [09:03:40] [Client thread/WARN] [FML/blockdrops]: \*  at mrriegel.blockdrops.BlockDrops.postInit(BlockDrops.java:131)...
> [09:03:40] [Client thread/WARN] [FML/blockdrops]: ****************************************

**Comment by KidsDontPlay** [comment]
you can add "mysticalcrops" do the blacklist in the config file.

try this one
https://github.com/MrRiegel/mrriegel.github.io/raw/master/BlockDrops-1.10.2-1.0.12.jar

**Comment by HendrikJ79** [comment]
with adding "mysticalcrops" to the blacklist it works fine now
