### ISSUE TITLE
Block Drops errored and CTDed

### ISSUE THREAD

**Issue by DatrixTHLK** [KidsDontPlay/BlockDrops#23]
Block Drops: 1.0.11
JEI: 3.10.0.261
Forge Version: 12.18.1.2092
Crash Report: http://pastebin.com/RPch9x5s
FML Log: http://www.pastefs.com/pid/5376

**Comment by KidsDontPlay** [comment]
try to add "mysticalcrops" do the blacklist in the config file.

**Comment by DatrixTHLK** [comment]
Will do.

**Comment by DatrixTHLK** [comment]
It worked but the only mod it is crashing at is Mattdehepic core and I tried blacklisting that mod and it won't cooperate with me.

**Comment by DatrixTHLK** [comment]
It worked. Thanks.
