### ISSUE TITLE
Compatibility issue with newer versions of JEI.

### ISSUE THREAD

**Issue by Zarepheth** [KidsDontPlay/BlockDrops#28]
I'm not sure whether the issue is with your JEI plugin or JEI itself, so I'll cross post this for both.

As the game attempts to load, I receive a LoaderExceptionModCrash exception which crashes the game to the desktop before I can even load a world. It seems to be related to the "mezz/jei/util/FakeClientPlayer" object.

Game Log with crash report: [paste.ee](https://paste.ee/p/kHJUY)

**Comment by Zarepheth** [comment]
@mezz says that [JEI was refactored](https://github.com/mezz/JustEnoughItems/issues/793#issuecomment-291752817) and the Block Drops plugin will have to be updated to work with the newer versions of JEI.

**Comment by ghost** [comment]
hi, i'm coming from [here](https://github.com/mezz/JustEnoughItems/issues/791), please help me
