### ISSUE TITLE
v1.1.1 conflict with RailCraft v10.1.0

### ISSUE THREAD

**Issue by Y0ungSandwich** [KidsDontPlay/BlockDrops#29]
Not sure who can fix what in this situation so I left the information on both githubs.
https://pastebin.com/S2hvzdkK
https://github.com/CovertJaguar/Railcraft/issues/1162

**Comment by KidsDontPlay** [comment]
I can't reproduce the crash.
Are you sure it's caused by railcraft?

**Comment by Y0ungSandwich** [comment]
Removing the newest version of railcraft allowed the pack to boot. I'm wondering if this has anything to do with JEI https://github.com/MrRiegel/BlockDrops/issues/28 since that was also updated.  But the two together don't crash. Only when RC update was introduced.  

Just re added the new version of RC in a local test build and crashed again. Removed it and replaced with previous version, loads just fine.

**Comment by KidsDontPlay** [comment]
[file.zip](https://github.com/MrRiegel/BlockDrops/files/948835/file.zip)
try this one. (you have to extract the jar file)

**Comment by Y0ungSandwich** [comment]
Didn't work. Covert Jaguar seems to have claimed its his mod and that it happens without Block Drops though I can not reproduce without the two being together. Sadly this means I might get a fix in 4-6 months :P Thanks for looking into it though!
