### ISSUE TITLE
Many drops breaks the display

### ISSUE THREAD

**Issue by BakermanLP** [KidsDontPlay/BlockDrops#3]
Sorry, me again :)

I've got another issue, but it is kind of cosmetic. This time a picture say's more than a thousand words:

![2016-06-17_13 48 00](https://cloud.githubusercontent.com/assets/3873443/16149637/78911a1e-3492-11e6-8b9d-f9e034a78a5a.png)

**Comment by KidsDontPlay** [comment]
Ja, hab ich schon gesehn. aber ich glaub das kann man in kauf nehmen. wer kaonnte auch damit rechnen, dass ein block so viel unterschiedliche drops hat.

**Comment by BakermanLP** [comment]
Stimmt. Ist verkraftbar :)

**Comment by KidsDontPlay** [comment]
kommt ja auch nich so oft vor. und dafür extra ne zweite reihe slots machen lohnt nich. wobei das in dem beispiel nich ma reichen würde
