### ISSUE TITLE
JsonSyntaxException

### ISSUE THREAD

**Issue by OrdinatorStouff** [KidsDontPlay/BlockDrops#34]
https://pastebin.com/8t2iwCYR

Forge 1.12.1 - 14.22.0.2460
blockdrops-1.12-1.3.0.jar 

Possibly some incompatibilities in new forge version? This wasn't my crash but one from a user on the ATM3 server that I have testing the latest forge build (mod works fine in Forge 2456)

**Comment by KidsDontPlay** [comment]
Show the blockdrops.txt file

**Comment by OrdinatorStouff** [comment]
I just tried with Forge 2464 and seemed to work fine so going to say I can no longer reproduce this. Thanks~
