### ISSUE TITLE
Mod doesn't recognise custom drops added by DropAnything

### ISSUE THREAD

**Issue by CelestialPhoenix** [KidsDontPlay/BlockDrops#35]
Minecraft version 1.10.2
Blockdrops version 1.1.1
DropAnything version 0.0.1
https://minecraft.curseforge.com/projects/dropanything

Blockdrops shows all the default drops just fine, however it does not list drops added by Drop Anything. 
The custom drops added by Drop Anything work fine when tested in world.

Manually adding entries to the BlockDrops.key does not resolve the issue.
```
  {
    "name": "quadrum:componentcast",
    "meta": 1,
    "length": 1,
    "name0": "gregtech:gtmetaitem01",
    "meta0": 28035,
    "0chance0": 800.0,
    "1chance0": 800.0,
    "2chance0": 800.0,
    "3chance0": 800.0,
    "0pair0": "{\n  \"left\": 1,\n  \"right\": 1\n}",
    "1pair0": "{\n  \"left\": 1,\n  \"right\": 1\n}",
    "2pair0": "{\n  \"left\": 1,\n  \"right\": 1\n}",
    "3pair0": "{\n  \"left\": 1,\n  \"right\": 1\n}"
  },
```
(this block drops 8 copper rings in game)

**Comment by KidsDontPlay** [comment]
Rename the blockdrops jar because drop anyhing is loaded after blocdrops.
This may work because forge loads mods alphabetically.

**Comment by CelestialPhoenix** [comment]
No luck renaming either BlockDrops as zzBlockDrops or DropAnything as aaDropAnything.

Also tried opening the BlockDrops.jar with 7zip and changing the modid to zzblockdrops in the mcmod.info file. 
This put the mod last in the loader mods list on multiMC, but still no luck in solving the issue in game.
