### ISSUE TITLE
Wrong drops (outdated blockdrops.txt file)

### ISSUE THREAD

**Issue by raspopov** [KidsDontPlay/BlockDrops#39]
Something is very wrong with latest 1.12.2-1.3.1 version... Many drops are missed (from wheat for example), and also there are some strange "empty drops":

![BlockDrops](https://i.imgur.com/89HQgVd.png)

JEI 4.8.0.117 + JER 0.8.6

**Comment by KidsDontPlay** [comment]
does the problem remains when you delete the `blockdrops.txt`?

**Comment by raspopov** [comment]
Yes, it helps. All empty recipes are gone (probably its from currently disabled mods).
Never noticed that file, why it's exists and no auto-refreshing?
