### ISSUE TITLE
Not sure why this is ocurring, but crashing on load

### ISSUE THREAD

**Issue by Chronomera** [KidsDontPlay/BlockDrops#41]
This oddly enough, happened out of the blue seemingly, even though it used to run fine?
[crash-2017-11-30_19.49.07-client.txt](https://github.com/MrRiegel/BlockDrops/files/1520362/crash-2017-11-30_19.49.07-client.txt)

**Comment by KidsDontPlay** [comment]
your json file is not formatted correctly.
delete `config/BlockDrops/blockdrops.txt`
