### ISSUE TITLE
Issues Processing - Silent Gems Drops

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [KidsDontPlay/BlockDrops#42]
[09:24:38] [pool-4-thread-636/ERROR] [blockdrops]: An error occured while calculating drops for tile.ChaosFlowerPot.name (class java.lang.NullPointerException)

Client Latest
https://gist.github.com/P3rf3ctXZer0/59e71fdbce102e754edb7a330b1e6f5f

Latest
https://gist.github.com/P3rf3ctXZer0/93b4356944c959edb129ef248168006b

I am not sure if any of this helps but its what I have.

**Comment by KidsDontPlay** [comment]
just ignore it.
some blocks are not compatible with this mod

**Comment by P3rf3ctXZer0** [comment]
Is there a way to simply disable a blockdrop check for a single block? I don't like ignoring issues. It tends to lead to pack stability issues.
