### ISSUE TITLE
[1.12.2] Startup problem (Unknown Reason)

### ISSUE THREAD

**Issue by Draskh** [KidsDontPlay/BlockDrops#44]
The crashes because of it ran out of memory. That happened every time block drop was present. In the loading screen you can see that it do not quit its process but in the crash log you can see nothing.
[crash-2018-01-07_01.35.12-client.txt.docx](https://github.com/MrRiegel/BlockDrops/files/1609841/crash-2018-01-07_01.35.12-client.txt.docx)

So I do not know how to solve this. The cause seems to be UniDict but if you remove UniDict the game crashes with another mod. That only ends if you remove Block Drops.

**Comment by KidsDontPlay** [comment]
change the blocks drops config to `B:multithreaded=true` and delete `blockdrops.txt`. that should fix it

**Comment by Draskh** [comment]
It did.
