### ISSUE TITLE
Request - Don't display block that be hidden in JEI

### ISSUE THREAD

**Issue by Snownee** [KidsDontPlay/BlockDrops#46]
Some blocks have been hidden in JEI may cause confuse

**Comment by KidsDontPlay** [comment]
what? can you explain more precisely?

**Comment by Snownee** [comment]
JEI has an edit mode to hide an item. Hidden items still show the drops

**Comment by KidsDontPlay** [comment]
So? Hidden items still show crafting recipes/furnace recipes as well

**Comment by Snownee** [comment]
But removing these recipes is much easier than tweaking drops

**Comment by KidsDontPlay** [comment]
I guess removing the blocks from the recipe list would be more confusing for many people.
Edit: so what do you want? removing the recipe if the input block is hidden or removing any hidden blocks in the output?
Edit2: did you ask mezz to make hidden items invisible in recipes as well?

**Comment by Snownee** [comment]
I am making a modpack and I plan to completely replace vanilla coal ore with Geolosys‘, but the problem is the previous recipe still shows so I guess it may confuse players.

1. Removing the recipe if the input block is hidden
2. No I didn't because I can simply remove a recipe by using CraftTweaker. But for drops it is more difficult to tweak drops and wasting time investigates hidden blocks seems unnecessary.

There is another solution: adding a blacklist for specific blocks

**Comment by KidsDontPlay** [comment]
It's not that difficult to remove drops from the list. open `config/BlockDrops/blockdrops.txt`, search for 'coal' and delete the entry.
I don't know if it is possible to hide recipes dynamically

**Comment by Snownee** [comment]
Thanks that will help.
