### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Wissi** [KidsDontPlay/BlockDrops#48]
Awesome mod we love your work.

We recently updated our modpack and the client is crashing:
```
java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
```
Client crash:
Full crash log [here](https://paste.dimdev.org/emojomiyop.mccrash)

If you need any more information, let me know. 
Thanks.

**Comment by KidsDontPlay** [comment]
seems the file is broken. you can delete it or try to fix it by using a json linter.
