### ISSUE TITLE
Right click and R key different.

### ISSUE THREAD

**Issue by JohnTravolta76** [KidsDontPlay/BlockDrops#51]
Hello, 
I have noticed there is a discrepancy between the right click and the R key. For example

Right clicking COBBLESTONE I get this: https://puu.sh/EqNf3/5d567ffd95.png
Pressing R I get this: https://puu.sh/EqNfp/c1c214113f.png

It only occurs sometimes for example - 
Right clicking STONE I get this: https://puu.sh/EqNgP/0a6a30271f.png
Block drops being a tab, as I suspect SHOULD happen.

**Comment by KidsDontPlay** [comment]
So why is this a problem? This is intentend behaviour.
R/left click shows recipes.
U/right click shows usages.
