### ISSUE TITLE
Block Drops Hangs at Phase 3 in launching modpack

### ISSUE THREAD

**Issue by RayzoRayy** [KidsDontPlay/BlockDrops#6]
Version BlockDrops-1.9.4-1.0.3 hangs for about a minute of Phase 3 when launching Minecraft and loading it up. No crash, just thought this might be something too look at.

**Comment by KidsDontPlay** [comment]
That's normal. I calculate the drops by simulating a block mining. The more blocks (e.g. Chisel)  you have the more it will take.  You could reduce the time by decreasing the iteration number in the config file.

**Comment by Xiaminou** [comment]
But does it need to do it every time? Unless the mods change it shouldn't have to do it again.

Mystcraft has a similar kind of profiling but it only does it once, unless you add new mods or update mods.

**Comment by Xiaminou** [comment]
Thanks.
