### ISSUE TITLE
[1.9.4] BlockDrops takes 2 minutes to load in PostInitialization

### ISSUE THREAD

**Issue by Xiaminou** [KidsDontPlay/BlockDrops#7]
I recently noticed that my launcher freezes during minecraft loading, at first I thought that it was minecraft benig derpy, however I realised that it always stopped on BlockDrops and after checking the loading log (LoadingProfiler) I found out that BlockDrops takes 132192ms in PostInitialization.

Loading Log: http://pastebin.com/KwtGgNkp
Client Log: https://drive.google.com/open?id=0BxQWn9jKBIAJTjQ1UkdNd1JNX1U

**Comment by KidsDontPlay** [comment]
Duplicate https://github.com/MrRiegel/BlockDrops/issues/6
